name: compound_me
description: A Personal Finance and Habit Tracker App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^1.1.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.1.0
  drift: ^2.14.0
  path_provider: ^2.1.2
  path: ^1.8.3
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  drift_dev: ^2.14.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
